function Hd = bandpass_elliptic_v1(fs)
%BANDPASS_ELLIPTIC_5_20_600_700 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 14-Nov-2016 18:31:39

% Elliptic Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

Fstop1 = 50*fs/2000;       % First Stopband Frequency
Fpass1 = 100*fs/2000;      % First Passband Frequency
Fpass2 = 200*fs/2000;     % Second Passband Frequency
Fstop2 = 250*fs/2000;     % Second Stopband Frequency
Astop1 = 80;      % First Stopband Attenuation (dB)
Apass  = 1;       % Passband Ripple (dB)
Astop2 = 80;      % Second Stopband Attenuation (dB)
match  = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'ellip', 'MatchExactly', match);

% [EOF]
